server:
  port: 8081
  forward-headers-strategy: native
swaggerfox:
   base-path: /docs

#logging:
#  level:
#    org.apache.kafka: WARN
#    br.org.fiergs: TRACE
#    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

spring:
  http:
    log-request-details: true
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  application:
    name: pedido
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: 
    password: 
    url: 
    hikari:
      validation-query: SELECT 1 FROM DUAL
      validation-timeout: 60000
  data:
    mongodb:
      uri: 
soap:
  service:
    wsdl: "http://wwwtest.sistemafiergs.org.br:7880/iif-core/pedidoDeVenda"
    namespace-url: "http://ws.iifcore.fiergs.org.br/"
    namespace-method-uri: "http://ws.iifcore.fiergs.org.br/"
    uri-siga: "http://wwwtest.sistemafiergs.org.br:7880/iif-core/pedidoDeVenda"
    wss-url: "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"
    port-name: PedidoDeVendaWsImplPort
    service-name: pedidoDeVenda
    username: 
    userkey: 
jasypt:
  encryptor:
    password: RoNGlA
