server:
  port: 8081
  forward-headers-strategy: native
swaggerfox:
   base-path: /docs

#logging:
#  level:
#    org.apache.kafka: WARN
#    br.org.fiergs: TRACE
#    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

spring:
  http:
    log-request-details: true
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  application:
    name: pedido
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: apims
    password: ENC(LbLCbQQCU9/cbDMObyYZ50h5vUJY8ACB)
    url: jdbc:oracle:thin:@//srvdes.sistemafiergs.org.br:1521/dbdes.srvdes.sistemafiergs.org.br
    hikari:
      validation-query: SELECT 1 FROM DUAL
      validation-timeout: 60000
  data:
    mongodb:
      uri: mongodb://fiergs_payment_username:f1eRG%24_M%40ngO@mongodb01-des.sistemafiergs.com.br:27017,mongodb02-des.sistemafiergs.com.br:27017,mongodb03-des.sistemafiergs.com.br:27017/fiergs-payment?replicaSet=rs0&maxIdleTimeMS=183200000&socketTimeoutMS=183200000&ssl=true
soap:
  service:
    wsdl: "http://wwwtest.sistemafiergs.org.br:7880/iif-core/pedidoDeVenda"
    namespace-url: "http://ws.iifcore.fiergs.org.br/"
    namespace-method-uri: "http://ws.iifcore.fiergs.org.br/"
    uri-siga: "http://wwwtest.sistemafiergs.org.br:7880/iif-core/pedidoDeVenda"
    wss-url: "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"
    port-name: PedidoDeVendaWsImplPort
    service-name: pedidoDeVenda
    username: daniel.chaves
    userkey: dbtest01
jasypt:
  encryptor:
    password: RoNGlA
app:
  bank-slip-api-key: b7>E9v#eQ!,UdbHEU*5]-vC<{j$3X`Pre`UpA2hz8CW%vBU-\NS66z3?f68w!pef
azure:
  storage:
    connection-string: DefaultEndpointsProtocol=https;AccountName=recinddevlocal;AccountKey=06Du33/Zm1j+4dNqze0UtYSybQ2BxIUIwY5YBRV60JWc0RhmKjcdAcQc+Oa1PwJMWxG/FPKtgRkF+AStQA1WQw==;EndpointSuffix=core.windows.net
    container-name: documents